server:
  port: 8080
  servlet:
    context-path: /task-management
spring:
  datasource:
    url : "jdbc:mysql://localhost:3306/task-management"
    username : root
    password : root
  jpa:
    show-sql: true